use ratatui::style::Color;

pub(crate) struct Theme {
    pub(crate) bg: Color,
    pub(crate) text: Color,
    pub(crate) muted: Color,
    pub(crate) dim: Color,
    pub(crate) blue: Color,
    pub(crate) purple: Color,
    pub(crate) pink: Color,
    pub(crate) danger: Color,
    pub(crate) green: Color,
    pub(crate) overlay: Color,
    pub(crate) scroll_thumb: Color,
    pub(crate) scroll_track: Color,
    pub(crate) status_active_bg: Color,
    pub(crate) user_bg: Color,
    pub(crate) code_bg: Color,
    pub(crate) rail: Color,
    pub(crate) thread_accent: Color,
    pub(crate) thought_bar: Color,
    pub(crate) thought_text: Color,
    pub(crate) footer_icon_color: Color,
    pub(crate) footer_primary: Color,
    pub(crate) footer_muted: Color,
    pub(crate) code_label: Color,
    pub(crate) mermaid_label: Color,
    pub(crate) mermaid_text: Color,
    pub(crate) rail_char: char,
    pub(crate) thought_bar_char: char,
    pub(crate) user_leading_bar: char,
    pub(crate) footer_icon: char,
    pub(crate) thread_gutter: usize,
    pub(crate) user_pad: usize,
    pub(crate) user_right_gap: usize,
    pub(crate) answer_left_pad: usize,
    pub(crate) answer_right_pad: usize,
}

impl Default for Theme {
    fn default() -> Self {
        Self {
            bg: Color::Rgb(12, 18, 32),
            text: Color::Rgb(232, 235, 245),
            muted: Color::Rgb(147, 156, 182),
            dim: Color::Rgb(67, 77, 105),
            blue: Color::Rgb(126, 160, 255),
            purple: Color::Rgb(185, 140, 255),
            pink: Color::Rgb(255, 120, 170),
            danger: Color::Rgb(255, 72, 72),
            green: Color::Rgb(91, 228, 155),
            overlay: Color::Rgb(10, 14, 28),
            scroll_thumb: Color::Rgb(218, 220, 228),
            scroll_track: Color::Rgb(107, 116, 144),
            status_active_bg: Color::Rgb(42, 38, 84),
            user_bg: Color::Rgb(32, 33, 36),
            code_bg: Color::Rgb(18, 20, 24),
            rail: Color::Rgb(150, 150, 156),
            thread_accent: Color::Rgb(0, 210, 230),
            thought_bar: Color::Rgb(150, 150, 156),
            thought_text: Color::Rgb(137, 137, 145),
            footer_icon_color: Color::Rgb(0, 210, 230),
            footer_primary: Color::Rgb(220, 223, 228),
            footer_muted: Color::Rgb(137, 137, 145),
            code_label: Color::Rgb(175, 180, 196),
            mermaid_label: Color::Rgb(175, 180, 196),
            mermaid_text: Color::Rgb(214, 218, 228),
            rail_char: '┃',
            thought_bar_char: '┃',
            user_leading_bar: '┃',
            footer_icon: '◻',
            thread_gutter: 1,
            user_pad: 1,
            user_right_gap: 3,
            answer_left_pad: 2,
            answer_right_pad: 4,
        }
    }
}
